"""add_riscos_missing_columns

Revision ID: 2e4c64609f95
Revises: g3h4i5j6k7l8
Create Date: 2026-02-08 14:19:14.846569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e4c64609f95'
down_revision: Union[str, None] = 'g3h4i5j6k7l8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portarias_designacao',
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('dfd_id_referencia', sa.Integer(), nullable=True, comment='ID do DFD aprovado que originou esta portaria'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('gerado_por_ia', sa.Boolean(), nullable=True),
    sa.Column('prompt_ia', sa.Text(), nullable=True),
    sa.Column('metadata_ia', sa.JSON(), nullable=True),
    sa.Column('campos_editados', sa.JSON(), nullable=True),
    sa.Column('campos_regenerados', sa.JSON(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('data_aprovacao', sa.DateTime(), nullable=True),
    sa.Column('protocolo_sei', sa.JSON(), nullable=True, comment='Protocolo de publicação no SEI'),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portarias_designacao_id'), 'portarias_designacao', ['id'], unique=False)
    op.alter_column('aviso_publicidade_direta', 'tr_id',
               existing_type=sa.INTEGER(),
               comment='TR vinculado ao aviso',
               existing_nullable=True)
    op.alter_column('aviso_publicidade_direta', 'fundamento_legal',
               existing_type=sa.VARCHAR(length=100),
               comment='Inciso específico do Art. 75 ou Art. 74 da Lei 14.133/21',
               existing_nullable=True)
    op.alter_column('aviso_publicidade_direta', 'artigo_lei',
               existing_type=sa.VARCHAR(length=50),
               comment="Ex: 'Art. 75, II' ou 'Art. 74, I'",
               existing_nullable=True)
    op.alter_column('aviso_publicidade_direta', 'justificativa_legal',
               existing_type=sa.TEXT(),
               comment='Explicação do enquadramento na hipótese de dispensa',
               existing_nullable=True)
    op.alter_column('aviso_publicidade_direta', 'valor_estimado',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Teto que a administração se propõe a pagar',
               existing_nullable=True)
    op.alter_column('aviso_publicidade_direta', 'metodologia_valor',
               existing_type=sa.TEXT(),
               comment='Como foi calculado o valor estimado',
               existing_nullable=True)
    op.alter_column('aviso_publicidade_direta', 'prazo_manifestacao_dias',
               existing_type=sa.INTEGER(),
               comment='Número de dias úteis para manifestação (mínimo 3 para dispensa eletrônica)',
               existing_nullable=True)
    op.alter_column('aviso_publicidade_direta', 'data_inicio_prazo',
               existing_type=sa.DATE(),
               comment='Data de início do prazo para manifestação',
               existing_nullable=True)
    op.alter_column('aviso_publicidade_direta', 'data_fim_prazo',
               existing_type=sa.DATE(),
               comment='Data de término do prazo para manifestação',
               existing_nullable=True)
    op.alter_column('aviso_publicidade_direta', 'data_publicacao_pncp',
               existing_type=postgresql.TIMESTAMP(),
               comment='Data de publicação no PNCP',
               existing_nullable=True)
    op.alter_column('aviso_publicidade_direta', 'link_pncp',
               existing_type=sa.VARCHAR(length=500),
               comment='Link para o aviso no Portal Nacional de Contratações Públicas',
               existing_nullable=True)
    op.alter_column('aviso_publicidade_direta', 'data_publicacao_site_orgao',
               existing_type=postgresql.TIMESTAMP(),
               comment='Data de publicação no site do órgão',
               existing_nullable=True)
    op.alter_column('aviso_publicidade_direta', 'link_site_orgao',
               existing_type=sa.VARCHAR(length=500),
               comment='Link para o aviso no site do órgão',
               existing_nullable=True)
    op.alter_column('aviso_publicidade_direta', 'numero_aviso',
               existing_type=sa.VARCHAR(length=50),
               comment='Número de identificação do aviso',
               existing_nullable=True)
    op.alter_column('aviso_publicidade_direta', 'extrato_aviso',
               existing_type=sa.TEXT(),
               comment='Extrato resumido do aviso publicado',
               existing_nullable=True)
    op.alter_column('aviso_publicidade_direta', 'protocolo_sei',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Protocolo de publicação no SEI',
               existing_nullable=True)
    op.alter_column('avisos_dispensa_eletronica', 'numero_aviso',
               existing_type=sa.VARCHAR(length=50),
               comment='Número do aviso atribuído pelo portal',
               existing_nullable=True)
    op.alter_column('avisos_dispensa_eletronica', 'data_publicacao',
               existing_type=postgresql.TIMESTAMP(),
               comment='Data de publicação no portal eletrônico',
               existing_nullable=True)
    op.alter_column('avisos_dispensa_eletronica', 'link_portal',
               existing_type=sa.VARCHAR(length=500),
               comment='URL do aviso no portal eletrônico',
               existing_nullable=True)
    op.alter_column('avisos_dispensa_eletronica', 'protocolo_publicacao',
               existing_type=sa.VARCHAR(length=50),
               comment='Número de protocolo do aviso publicado',
               existing_nullable=True)
    op.alter_column('avisos_dispensa_eletronica', 'protocolo_sei',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Protocolo de publicação no SEI',
               existing_nullable=True)
    op.alter_column('certidoes_enquadramento', 'limite_legal_aplicavel',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Limite legal para enquadramento (ex: R$ 8.800)',
               existing_nullable=True)
    op.alter_column('certidoes_enquadramento', 'valor_contratacao_analisada',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Valor da contratação analisada',
               existing_nullable=True)
    op.alter_column('certidoes_enquadramento', 'conclusao_enquadramento',
               existing_type=sa.TEXT(),
               comment='Conclusão sobre o enquadramento legal',
               existing_nullable=True)
    op.alter_column('certidoes_enquadramento', 'artigo_lei_aplicavel',
               existing_type=sa.VARCHAR(length=50),
               comment='Artigo da Lei 14.133/21 aplicável (ex: Art. 75, I)',
               existing_nullable=True)
    op.alter_column('certidoes_enquadramento', 'responsavel_certificacao',
               existing_type=sa.VARCHAR(length=200),
               comment='Nome e cargo do responsável',
               existing_nullable=True)
    op.alter_column('certidoes_enquadramento', 'protocolo_sei',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Protocolo de publicação no SEI',
               existing_nullable=True)
    op.alter_column('checklist_conformidade', 'tr_id',
               existing_type=sa.INTEGER(),
               comment='TR vinculado ao checklist',
               existing_nullable=True)
    op.alter_column('checklist_conformidade', 'itens_verificacao',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='JSON: [{item, descricao, status, referencia_folhas, observacoes}, ...]. Status: sim/nao/nao_se_aplica',
               existing_nullable=True)
    op.alter_column('checklist_conformidade', 'dfd_presente',
               existing_type=sa.VARCHAR(length=20),
               comment='Enum: sim, nao, nao_se_aplica',
               existing_nullable=True)
    op.alter_column('checklist_conformidade', 'dfd_folhas',
               existing_type=sa.VARCHAR(length=100),
               comment='Referência de páginas/ID no processo',
               existing_nullable=True)
    op.alter_column('checklist_conformidade', 'etp_presente',
               existing_type=sa.VARCHAR(length=20),
               comment='Enum: sim, nao, nao_se_aplica',
               existing_nullable=True)
    op.alter_column('checklist_conformidade', 'tr_presente',
               existing_type=sa.VARCHAR(length=20),
               comment='Enum: sim, nao, nao_se_aplica',
               existing_nullable=True)
    op.alter_column('checklist_conformidade', 'matriz_riscos_presente',
               existing_type=sa.VARCHAR(length=20),
               comment='Enum: sim, nao, nao_se_aplica',
               existing_nullable=True)
    op.alter_column('checklist_conformidade', 'disponibilidade_orcamentaria_presente',
               existing_type=sa.VARCHAR(length=20),
               comment='Enum: sim, nao, nao_se_aplica',
               existing_nullable=True)
    op.alter_column('checklist_conformidade', 'parecer_juridico_presente',
               existing_type=sa.VARCHAR(length=20),
               comment='Enum: sim, nao, nao_se_aplica',
               existing_nullable=True)
    op.alter_column('checklist_conformidade', 'validado_por',
               existing_type=sa.VARCHAR(length=200),
               comment='Nome e cargo da autoridade que validou',
               existing_nullable=True)
    op.alter_column('checklist_conformidade', 'assinatura_eletronica',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='JSON: {nome, cargo, cpf, data, hash_assinatura}',
               existing_nullable=True)
    op.alter_column('checklist_conformidade', 'observacoes_gerais',
               existing_type=sa.TEXT(),
               comment='Observações ou pendências identificadas',
               existing_nullable=True)
    op.alter_column('checklist_conformidade', 'status_conformidade',
               existing_type=sa.VARCHAR(length=50),
               comment='Enum: conforme, nao_conforme, conforme_com_ressalvas',
               existing_nullable=True)
    op.alter_column('checklist_conformidade', 'protocolo_sei',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Protocolo de publicação no SEI',
               existing_nullable=True)
    op.alter_column('etps', 'solucao_escolhida',
               existing_type=sa.VARCHAR(length=200),
               comment='Nome/tipo da solução escolhida',
               existing_comment='Nome/tipo da solução escolhida: Compra, Locação, SaaS, etc',
               existing_nullable=True)
    op.alter_column('etps', 'contratacoes_correlatas',
               existing_type=sa.TEXT(),
               comment='Contratações interdependentes',
               existing_comment='Contratações interdependentes (ex: Ar Condicionado -> Instalação Elétrica)',
               existing_nullable=True)
    op.alter_column('etps', 'sincronizado',
               existing_type=sa.INTEGER(),
               comment='1=sincronizado, 0=módulo fonte alterado',
               existing_comment='1=sincronizado, 0=módulo fonte alterado, precisa revisão',
               existing_nullable=True)
    op.alter_column('etps', 'checklist_conformidade',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='JSON: {valor_presente: bool, parcelamento_justificado: bool, riscos_citados: bool, pca_mencionado: bool}',
               existing_nullable=True)
    op.alter_column('etps', 'adesao_ata_habilitada',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment='Usuário habilitou busca por adesão em ata de registro de preços',
               existing_server_default=sa.text('false'))
    op.alter_column('etps', 'fase_adesao_ata',
               existing_type=sa.VARCHAR(length=50),
               comment='Enum: nao_iniciada, buscando_atas, ata_selecionada, deep_research_ativo, concluida',
               existing_nullable=True)
    op.alter_column('etps', 'ata_selecionada',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='JSON com dados da ata selecionada',
               existing_nullable=True)
    op.alter_column('etps', 'deep_research_ativado',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment='Flag para indicar que deep_research foi automaticamente ativado',
               existing_server_default=sa.text('false'))
    op.alter_column('etps', 'modalidade_sugerida',
               existing_type=sa.VARCHAR(length=50),
               comment='Enum: adesao_ata, dispensa_valor_baixo, licitacao_normal',
               existing_nullable=True)
    op.alter_column('etps', 'modalidade_definida',
               existing_type=sa.VARCHAR(length=50),
               comment='Enum: adesao_ata, dispensa_valor_baixo, licitacao_normal, contratacao_direta',
               existing_nullable=True)
    op.alter_column('etps', 'data_definicao_modalidade',
               existing_type=postgresql.TIMESTAMP(),
               comment='Data em que modalidade foi definida pelo usuário',
               existing_nullable=True)
    op.alter_column('etps', 'justificativa_modalidade',
               existing_type=sa.TEXT(),
               comment='Justificativa técnica/legal para escolha da modalidade',
               existing_nullable=True)
    op.alter_column('etps', 'criterios_analise_modalidade',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='JSON: {valor_limite: float, adesao_atas_disponiveis: bool, etc}',
               existing_nullable=True)
    op.add_column('itens_risco', sa.Column('versao', sa.Integer(), nullable=False))
    op.add_column('itens_risco', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('itens_risco', sa.Column('gerado_por_ia', sa.Boolean(), nullable=True))
    op.add_column('itens_risco', sa.Column('prompt_ia', sa.Text(), nullable=True))
    op.add_column('itens_risco', sa.Column('metadata_ia', sa.JSON(), nullable=True))
    op.add_column('itens_risco', sa.Column('campos_editados', sa.JSON(), nullable=True))
    op.add_column('itens_risco', sa.Column('campos_regenerados', sa.JSON(), nullable=True))
    op.add_column('itens_risco', sa.Column('data_aprovacao', sa.DateTime(), nullable=True))
    op.add_column('itens_risco', sa.Column('protocolo_sei', sa.JSON(), nullable=True, comment='Protocolo de publicação no SEI'))
    op.alter_column('itens_risco', 'origem',
               existing_type=sa.VARCHAR(length=50),
               comment='Enum: DFD, Cotacao, PAC, Externo',
               existing_comment='Enum: DFD, Cotacao, PAC, Externo. Rastreabilidade da IA.',
               existing_nullable=True)
    op.alter_column('itens_risco', 'evento',
               existing_type=sa.TEXT(),
               comment='O QUÊ pode acontecer?',
               existing_comment="O QUÊ pode acontecer? Ex: 'Fornecedor não entregar no prazo'",
               existing_nullable=True)
    op.alter_column('itens_risco', 'causa',
               existing_type=sa.TEXT(),
               comment='POR QUÊ?',
               existing_comment="POR QUÊ? IA preenche analisando DFD+Cotações. Ex: 'Cotação com cronograma otimista'",
               existing_nullable=True)
    op.alter_column('itens_risco', 'consequencia',
               existing_type=sa.TEXT(),
               comment='QUAL IMPACTO?',
               existing_comment="QUAL IMPACTO? Ex: 'Paralisação do serviço público'",
               existing_nullable=True)
    op.alter_column('itens_risco', 'probabilidade',
               existing_type=sa.INTEGER(),
               comment='1-5: 1=Improvável, 5=Muito provável',
               existing_comment='1-5: 1=Improvável, 3=Médio, 5=Muito provável',
               existing_nullable=True)
    op.alter_column('itens_risco', 'impacto',
               existing_type=sa.INTEGER(),
               comment='1-5: 1=Irrelevante, 5=Catastrófico',
               existing_comment='1-5: 1=Irrelevante, 3=Médio, 5=Catastrófico',
               existing_nullable=True)
    op.alter_column('itens_risco', 'nivel_risco',
               existing_type=sa.INTEGER(),
               comment='Calculado: probabilidade × impacto (1-25)',
               existing_comment='Calculado: probabilidade × impacto (1-25). Mapeado: 1-5=Baixo, 6-10=Médio, 11-20=Alto, 21-25=Extremo',
               existing_nullable=True)
    op.alter_column('itens_risco', 'justificativa_probabilidade',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment="Ex: 'Baseado em histórico: 2 de 5 contratos anteriores atrasaram'",
               existing_nullable=True)
    op.alter_column('itens_risco', 'justificativa_impacto',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment="Ex: 'Atraso de 1 mês = perda de 30 dias de serviço. Impacto em X% da operação'",
               existing_nullable=True)
    op.alter_column('itens_risco', 'acoes_preventivas',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment="Fazer ANTES para evitar. Ex: 'Exigir atestado técnico rigoroso'",
               existing_nullable=True)
    op.alter_column('itens_risco', 'acoes_contingencia',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment="Fazer SE OCORRER. Ex: 'Acionar fornecedor número 2'",
               existing_nullable=True)
    op.alter_column('itens_risco', 'alocacao_responsavel',
               existing_type=sa.VARCHAR(length=50),
               comment='Enum: Contratante, Contratada, Compartilhado',
               existing_comment='Enum: Contratante, Contratada, Compartilhado. Quem paga a conta?',
               existing_nullable=True)
    op.alter_column('itens_risco', 'gatilho_monitoramento',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment="Sinal de alerta. Ex: 'Atraso de mais de 5 dias no cronograma'",
               existing_nullable=True)
    op.alter_column('itens_risco', 'responsavel_monitoramento',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Quem monitora? Ex: 'Gestor do Contrato'",
               existing_nullable=True)
    op.alter_column('itens_risco', 'criado_por',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Quem criou: usuário ou IA?',
               existing_nullable=True)
    op.alter_column('itens_risco', 'notas',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Anotações adicionais ou mudanças de status',
               existing_nullable=True)
    op.alter_column('justificativa_fornecedor_escolhido', 'aviso_id',
               existing_type=sa.INTEGER(),
               comment='Aviso de dispensa vinculado',
               existing_nullable=True)
    op.alter_column('justificativa_fornecedor_escolhido', 'nome_fornecedor',
               existing_type=sa.VARCHAR(length=300),
               comment='Razão social do fornecedor escolhido',
               existing_nullable=True)
    op.alter_column('justificativa_fornecedor_escolhido', 'cnpj_fornecedor',
               existing_type=sa.VARCHAR(length=20),
               comment='CNPJ do fornecedor',
               existing_nullable=True)
    op.alter_column('justificativa_fornecedor_escolhido', 'endereco_fornecedor',
               existing_type=sa.TEXT(),
               comment='Endereço completo do fornecedor',
               existing_nullable=True)
    op.alter_column('justificativa_fornecedor_escolhido', 'qualificacao_tecnica',
               existing_type=sa.TEXT(),
               comment='Provas de expertise única ou capacidade imediata',
               existing_nullable=True)
    op.alter_column('justificativa_fornecedor_escolhido', 'atestados_capacidade',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='JSON: [{tipo_atestado, descricao, data_emissao, orgao_emissor}, ...]',
               existing_nullable=True)
    op.alter_column('justificativa_fornecedor_escolhido', 'experiencia_comprovada',
               existing_type=sa.TEXT(),
               comment='Descrição da experiência comprovada do fornecedor',
               existing_nullable=True)
    op.alter_column('justificativa_fornecedor_escolhido', 'certidao_federal',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='JSON: {numero, data_emissao, validade, situacao}',
               existing_nullable=True)
    op.alter_column('justificativa_fornecedor_escolhido', 'certidao_estadual',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='JSON: {numero, data_emissao, validade, situacao}',
               existing_nullable=True)
    op.alter_column('justificativa_fornecedor_escolhido', 'certidao_municipal',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='JSON: {numero, data_emissao, validade, situacao}',
               existing_nullable=True)
    op.alter_column('justificativa_fornecedor_escolhido', 'certidao_fgts',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='JSON: {numero, data_emissao, validade, situacao}',
               existing_nullable=True)
    op.alter_column('justificativa_fornecedor_escolhido', 'certidao_trabalhista',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='JSON: {numero, data_emissao, validade, situacao}',
               existing_nullable=True)
    op.alter_column('justificativa_fornecedor_escolhido', 'certidoes_anexadas',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='JSON: [{tipo, arquivo, data_upload}, ...] - Conjunto completo de certidões',
               existing_nullable=True)
    op.alter_column('justificativa_fornecedor_escolhido', 'inviabilidade_competicao',
               existing_type=sa.VARCHAR(length=20),
               comment='Enum: sim, nao',
               existing_nullable=True)
    op.alter_column('justificativa_fornecedor_escolhido', 'justificativa_inviabilidade',
               existing_type=sa.TEXT(),
               comment='Explicação de por que não é possível licitar (ex: fornecedor exclusivo, artista consagrado)',
               existing_nullable=True)
    op.alter_column('justificativa_fornecedor_escolhido', 'tipo_inviabilidade',
               existing_type=sa.VARCHAR(length=100),
               comment="Ex: 'Fornecedor Exclusivo', 'Notória Especialização', 'Artista Consagrado'",
               existing_nullable=True)
    op.alter_column('justificativa_fornecedor_escolhido', 'documentacao_exclusividade',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='JSON: [{tipo_documento, descricao, arquivo}, ...] - Documentos que comprovam exclusividade',
               existing_nullable=True)
    op.alter_column('justificativa_fornecedor_escolhido', 'preco_proposto',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Preço proposto pelo fornecedor escolhido',
               existing_nullable=True)
    op.alter_column('justificativa_fornecedor_escolhido', 'analise_compatibilidade_preco',
               existing_type=sa.TEXT(),
               comment='Análise de compatibilidade do preço com valores de mercado',
               existing_nullable=True)
    op.alter_column('justificativa_fornecedor_escolhido', 'valores_referencia',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='JSON: [{fonte, valor, data}, ...] - Valores de referência para comparação',
               existing_nullable=True)
    op.alter_column('justificativa_fornecedor_escolhido', 'conclusao_justificativa',
               existing_type=sa.TEXT(),
               comment='Conclusão sobre a adequação do fornecedor e a conformidade da escolha',
               existing_nullable=True)
    op.alter_column('justificativa_fornecedor_escolhido', 'protocolo_sei',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Protocolo de publicação no SEI',
               existing_nullable=True)
    op.alter_column('justificativas_preco_escolha', 'justificativa_fornecedor',
               existing_type=sa.TEXT(),
               comment='Motivos da escolha deste fornecedor específico',
               existing_nullable=True)
    op.alter_column('justificativas_preco_escolha', 'analise_preco_praticado',
               existing_type=sa.TEXT(),
               comment='Análise do preço praticado vs mercado',
               existing_nullable=True)
    op.alter_column('justificativas_preco_escolha', 'preco_final_contratacao',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Preço final negociado para a contratação',
               existing_nullable=True)
    op.alter_column('justificativas_preco_escolha', 'protocolo_sei',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Protocolo de publicação no SEI',
               existing_nullable=True)
    op.alter_column('justificativas_vantagem_adesao', 'fundamentacao_legal',
               existing_type=sa.TEXT(),
               comment='Citação da Lei 14.133/21, Art. 37 e jurisprudência aplicável',
               existing_nullable=True)
    op.alter_column('justificativas_vantagem_adesao', 'justificativa_conveniencia',
               existing_type=sa.TEXT(),
               comment='Por que adesão é mais conveniente que contratação direta',
               existing_nullable=True)
    op.alter_column('justificativas_vantagem_adesao', 'declaracao_conformidade',
               existing_type=sa.TEXT(),
               comment='Declara conformidade com Lei 14.133/21 e regulamentos internos',
               existing_nullable=True)
    op.alter_column('justificativas_vantagem_adesao', 'protocolo_sei',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Protocolo de publicação no SEI',
               existing_nullable=True)
    op.alter_column('minuta_contrato', 'edital_id',
               existing_type=sa.INTEGER(),
               comment='Edital ao qual esta minuta está vinculada',
               existing_nullable=True)
    op.alter_column('minuta_contrato', 'obrigacoes_contratada',
               existing_type=sa.TEXT(),
               comment='Responsabilidades da contratada',
               existing_nullable=True)
    op.alter_column('minuta_contrato', 'obrigacoes_contratante',
               existing_type=sa.TEXT(),
               comment='Responsabilidades da contratante',
               existing_nullable=True)
    op.alter_column('minuta_contrato', 'obrigacoes_estruturadas',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='JSON: {contratada: [{clausula, descricao}, ...], contratante: [{clausula, descricao}, ...]}',
               existing_nullable=True)
    op.alter_column('minuta_contrato', 'forma_pagamento',
               existing_type=sa.TEXT(),
               comment='Descrição da forma de pagamento',
               existing_nullable=True)
    op.alter_column('minuta_contrato', 'prazo_pagamento',
               existing_type=sa.VARCHAR(length=100),
               comment="Ex: '30 dias após apresentação da nota fiscal'",
               existing_nullable=True)
    op.alter_column('minuta_contrato', 'fluxo_liquidacao',
               existing_type=sa.TEXT(),
               comment='Fluxo de liquidação e emissão de nota fiscal',
               existing_nullable=True)
    op.alter_column('minuta_contrato', 'data_inicio',
               existing_type=sa.DATE(),
               comment='Data de início do contrato',
               existing_nullable=True)
    op.alter_column('minuta_contrato', 'data_termino',
               existing_type=sa.DATE(),
               comment='Data de término do contrato',
               existing_nullable=True)
    op.alter_column('minuta_contrato', 'prazo_vigencia',
               existing_type=sa.VARCHAR(length=100),
               comment="Ex: '12 meses'",
               existing_nullable=True)
    op.alter_column('minuta_contrato', 'possibilidade_prorrogacao',
               existing_type=sa.VARCHAR(length=20),
               comment='Enum: sim, nao',
               existing_nullable=True)
    op.alter_column('minuta_contrato', 'condicoes_prorrogacao',
               existing_type=sa.TEXT(),
               comment='Condições para prorrogação do contrato',
               existing_nullable=True)
    op.alter_column('minuta_contrato', 'prazo_maximo_prorrogacao',
               existing_type=sa.VARCHAR(length=100),
               comment="Ex: 'Até 60 meses conforme Art. 107 da Lei 14.133/21'",
               existing_nullable=True)
    op.alter_column('minuta_contrato', 'exige_garantia',
               existing_type=sa.VARCHAR(length=20),
               comment='Enum: sim, nao',
               existing_nullable=True)
    op.alter_column('minuta_contrato', 'tipo_garantia',
               existing_type=sa.VARCHAR(length=100),
               comment="Ex: 'Seguro-garantia, caução em dinheiro, fiança bancária'",
               existing_nullable=True)
    op.alter_column('minuta_contrato', 'percentual_garantia',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Percentual sobre o valor do contrato (ex: 5%)',
               existing_nullable=True)
    op.alter_column('minuta_contrato', 'valor_garantia',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Valor da garantia em R$',
               existing_nullable=True)
    op.alter_column('minuta_contrato', 'rescisao',
               existing_type=sa.TEXT(),
               comment='Condições de rescisão do contrato',
               existing_nullable=True)
    op.alter_column('minuta_contrato', 'penalidades',
               existing_type=sa.TEXT(),
               comment='Penalidades por descumprimento',
               existing_nullable=True)
    op.alter_column('minuta_contrato', 'lei_aplicavel',
               existing_type=sa.TEXT(),
               comment='Lei e regulamentos aplicáveis ao contrato',
               existing_nullable=True)
    op.alter_column('minuta_contrato', 'foro_competente',
               existing_type=sa.VARCHAR(length=200),
               comment='Foro competente para dirimir conflitos',
               existing_nullable=True)
    op.alter_column('minuta_contrato', 'protocolo_sei',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Protocolo de publicação no SEI',
               existing_nullable=True)
    op.alter_column('pesquisas_precos', 'item_descricao',
               existing_type=sa.VARCHAR(length=500),
               comment='Descricao do item principal',
               existing_comment='Descricao do item principal (ex: Cafe, Acucar)',
               existing_nullable=True)
    op.alter_column('pesquisas_precos', 'document_header',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Cabecalho do documento',
               existing_comment='Cabecalho do documento (titulo, numero, versao)',
               existing_nullable=True)
    op.alter_column('pesquisas_precos', 'audit_metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Metadados de auditoria',
               existing_comment='Metadados de auditoria (modelo IA, tokens, timestamp)',
               existing_nullable=True)
    op.alter_column('relatorios_vantagem_economica', 'comparativo_precos',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='JSON: [{fornecedor, preco_ata, preco_direto, economia_percentual}, ...]',
               existing_nullable=True)
    op.alter_column('relatorios_vantagem_economica', 'custo_processamento_adesao',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Custos administrativos da adesão',
               existing_nullable=True)
    op.alter_column('relatorios_vantagem_economica', 'custo_processamento_direto',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Custos administrativos de contratação direta',
               existing_nullable=True)
    op.alter_column('relatorios_vantagem_economica', 'conclusao_tecnica',
               existing_type=sa.TEXT(),
               comment='Conclusão técnica sobre a vantagem econômica',
               existing_nullable=True)
    op.alter_column('relatorios_vantagem_economica', 'percentual_economia',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Percentual de economia (%)',
               existing_nullable=True)
    op.alter_column('relatorios_vantagem_economica', 'valor_economia_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Valor economizado (R$)',
               existing_nullable=True)
    op.alter_column('relatorios_vantagem_economica', 'protocolo_sei',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Protocolo de publicação no SEI',
               existing_nullable=True)
    op.add_column('riscos', sa.Column('prazo_execucao', sa.String(length=100), nullable=True, comment="Ex: '12 meses', '24 meses'"))
    op.add_column('riscos', sa.Column('modalidade_contratacao', sa.String(length=50), nullable=True, comment='Enum: Pregão, Concorrência, Dispensa, Inexigibilidade'))
    op.add_column('riscos', sa.Column('estrategia_geral', sa.Text(), nullable=True, comment='Resumo da estratégia de gestão de riscos do processo'))
    op.add_column('riscos', sa.Column('apetite_risco', sa.String(length=20), nullable=True, comment='Enum: Conservador, Moderado, Agressivo. Define nível aceitável de risco'))
    op.add_column('riscos', sa.Column('responsavel_pgr', sa.String(length=200), nullable=True, comment='Nome e cargo do responsável pelo PGR'))
    op.add_column('riscos', sa.Column('data_elaboracao', sa.DateTime(), nullable=True))
    op.alter_column('riscos', 'artefatos_base',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='IDs dos artefatos usados na análise',
               existing_comment='IDs dos artefatos usados na análise: {dfd_id: [1,2,3], etp_id: 5, cotacao_id: 7}',
               existing_nullable=True)
    op.alter_column('riscos', 'identificacao_objeto',
               existing_type=sa.TEXT(),
               comment='Resumo do que está sendo licitado',
               existing_comment="Resumo do que está sendo licitado (ex: 'Aquisição de Servidor Web')",
               existing_nullable=True)
    op.alter_column('riscos', 'valor_estimado_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Valor total da contratação (R$)',
               existing_comment='Valor total estimado derivado de cotações/ETP',
               existing_nullable=True)
    op.alter_column('riscos', 'data_revisao',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='Última revisão do PGR',
               existing_nullable=True)
    op.drop_column('riscos', 'metodologia_adotada')
    op.drop_column('riscos', 'resumo_analise_selecao')
    op.drop_column('riscos', 'mapa_calor')
    op.drop_column('riscos', 'resumo_analise_gestao')
    op.drop_column('riscos', 'content_blocks')
    op.drop_column('riscos', 'resumo_analise_planejamento')
    op.drop_column('riscos', 'equipe_responsavel')
    op.drop_column('riscos', 'plano_comunicacao')
    op.drop_column('riscos', 'matriz_alocacao')
    op.drop_column('riscos', 'document_header')
    op.drop_column('riscos', 'audit_metadata')
    op.alter_column('skills', 'ativa',
               existing_type=sa.BOOLEAN(),
               comment='Se a skill esta ativa globalmente',
               existing_comment='Se a skill esta ativa',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('skills', 'usuario_id',
               existing_type=sa.INTEGER(),
               comment='ID do usuario criador. Null para skills do sistema',
               existing_comment='ID do usuario criador',
               existing_nullable=True)
    op.alter_column('skills', 'tools',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment="Lista de ferramentas habilitadas pela skill. Ex: ['web_search', 'check_compliance']",
               existing_comment='Lista de ferramentas habilitadas pela skill',
               existing_nullable=True)
    op.alter_column('skills', 'textos_base',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Base de conhecimento textual (full-text) para injetar no prompt',
               existing_comment='Base de conhecimento textual (full-text)',
               existing_nullable=True)
    op.alter_column('termos_aceite_fornecedor', 'descricao_objeto_aceito',
               existing_type=sa.TEXT(),
               comment='Descrição detalhada do objeto aceito da ata',
               existing_nullable=True)
    op.alter_column('termos_aceite_fornecedor', 'preco_aceito',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Preço final aceito da ata',
               existing_nullable=True)
    op.alter_column('termos_aceite_fornecedor', 'documentos_anexados',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='JSON: [{tipo, nome_arquivo, data_upload, tamanho}, ...]',
               existing_nullable=True)
    op.alter_column('termos_aceite_fornecedor', 'responsaveis_assinatura',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='JSON: [{nome, cargo, data}, ...]',
               existing_nullable=True)
    op.alter_column('termos_aceite_fornecedor', 'protocolo_sei',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Protocolo de publicação no SEI',
               existing_nullable=True)
    op.alter_column('trs_simplificados', 'especificacao_objeto',
               existing_type=sa.TEXT(),
               comment='Especificação técnica do objeto (simplificada)',
               existing_nullable=True)
    op.alter_column('trs_simplificados', 'criterios_qualidade_simplificados',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='JSON: [{criterio, descricao}, ...]',
               existing_nullable=True)
    op.alter_column('trs_simplificados', 'prazos_simplificados',
               existing_type=sa.TEXT(),
               comment='Prazos resumidos de execução/entrega',
               existing_nullable=True)
    op.alter_column('trs_simplificados', 'valor_referencia_dispensa',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Valor de referência para justificar dispensa',
               existing_nullable=True)
    op.alter_column('trs_simplificados', 'justificativa_dispensa_valor',
               existing_type=sa.TEXT(),
               comment='Por que valor baixo justifica esta dispensa',
               existing_nullable=True)
    op.alter_column('trs_simplificados', 'protocolo_sei',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Protocolo de publicação no SEI',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trs_simplificados', 'protocolo_sei',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Protocolo de publicação no SEI',
               existing_nullable=True)
    op.alter_column('trs_simplificados', 'justificativa_dispensa_valor',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Por que valor baixo justifica esta dispensa',
               existing_nullable=True)
    op.alter_column('trs_simplificados', 'valor_referencia_dispensa',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Valor de referência para justificar dispensa',
               existing_nullable=True)
    op.alter_column('trs_simplificados', 'prazos_simplificados',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Prazos resumidos de execução/entrega',
               existing_nullable=True)
    op.alter_column('trs_simplificados', 'criterios_qualidade_simplificados',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='JSON: [{criterio, descricao}, ...]',
               existing_nullable=True)
    op.alter_column('trs_simplificados', 'especificacao_objeto',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Especificação técnica do objeto (simplificada)',
               existing_nullable=True)
    op.alter_column('termos_aceite_fornecedor', 'protocolo_sei',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Protocolo de publicação no SEI',
               existing_nullable=True)
    op.alter_column('termos_aceite_fornecedor', 'responsaveis_assinatura',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='JSON: [{nome, cargo, data}, ...]',
               existing_nullable=True)
    op.alter_column('termos_aceite_fornecedor', 'documentos_anexados',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='JSON: [{tipo, nome_arquivo, data_upload, tamanho}, ...]',
               existing_nullable=True)
    op.alter_column('termos_aceite_fornecedor', 'preco_aceito',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Preço final aceito da ata',
               existing_nullable=True)
    op.alter_column('termos_aceite_fornecedor', 'descricao_objeto_aceito',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Descrição detalhada do objeto aceito da ata',
               existing_nullable=True)
    op.alter_column('skills', 'textos_base',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Base de conhecimento textual (full-text)',
               existing_comment='Base de conhecimento textual (full-text) para injetar no prompt',
               existing_nullable=True)
    op.alter_column('skills', 'tools',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Lista de ferramentas habilitadas pela skill',
               existing_comment="Lista de ferramentas habilitadas pela skill. Ex: ['web_search', 'check_compliance']",
               existing_nullable=True)
    op.alter_column('skills', 'usuario_id',
               existing_type=sa.INTEGER(),
               comment='ID do usuario criador',
               existing_comment='ID do usuario criador. Null para skills do sistema',
               existing_nullable=True)
    op.alter_column('skills', 'ativa',
               existing_type=sa.BOOLEAN(),
               comment='Se a skill esta ativa',
               existing_comment='Se a skill esta ativa globalmente',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.add_column('riscos', sa.Column('audit_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Metadados de auditoria (modelo IA, tokens, timestamp)'))
    op.add_column('riscos', sa.Column('document_header', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Cabecalho do documento (titulo, numero, versao)'))
    op.add_column('riscos', sa.Column('matriz_alocacao', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Agrupa riscos por alocacao_responsavel: {Contratante: [...], Contratada: [...], Compartilhado: [...]}'))
    op.add_column('riscos', sa.Column('plano_comunicacao', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='JSON: [{stakeholder, formato, frequencia, conteudo}, ...]'))
    op.add_column('riscos', sa.Column('equipe_responsavel', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment="JSON: [{nome: 'João', cargo: 'Analista'}, ...]"))
    op.add_column('riscos', sa.Column('resumo_analise_planejamento', sa.TEXT(), autoincrement=False, nullable=True, comment='Sumarização de riscos da fase de planejamento'))
    op.add_column('riscos', sa.Column('content_blocks', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Estrutura JSON completa (legado)'))
    op.add_column('riscos', sa.Column('resumo_analise_gestao', sa.TEXT(), autoincrement=False, nullable=True, comment='Sumarização de riscos da fase de gestão contratual'))
    op.add_column('riscos', sa.Column('mapa_calor', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='JSON estruturado para renderizar matriz de prob vs impacto'))
    op.add_column('riscos', sa.Column('resumo_analise_selecao', sa.TEXT(), autoincrement=False, nullable=True, comment='Sumarização de riscos da fase de seleção'))
    op.add_column('riscos', sa.Column('metodologia_adotada', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment="Ex: 'Matriz 5x5', 'ISO 31000'"))
    op.alter_column('riscos', 'data_revisao',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               comment='Última revisão do PGR',
               existing_nullable=True)
    op.alter_column('riscos', 'valor_estimado_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Valor total estimado derivado de cotações/ETP',
               existing_comment='Valor total da contratação (R$)',
               existing_nullable=True)
    op.alter_column('riscos', 'identificacao_objeto',
               existing_type=sa.TEXT(),
               comment="Resumo do que está sendo licitado (ex: 'Aquisição de Servidor Web')",
               existing_comment='Resumo do que está sendo licitado',
               existing_nullable=True)
    op.alter_column('riscos', 'artefatos_base',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='IDs dos artefatos usados na análise: {dfd_id: [1,2,3], etp_id: 5, cotacao_id: 7}',
               existing_comment='IDs dos artefatos usados na análise',
               existing_nullable=True)
    op.drop_column('riscos', 'data_elaboracao')
    op.drop_column('riscos', 'responsavel_pgr')
    op.drop_column('riscos', 'apetite_risco')
    op.drop_column('riscos', 'estrategia_geral')
    op.drop_column('riscos', 'modalidade_contratacao')
    op.drop_column('riscos', 'prazo_execucao')
    op.alter_column('relatorios_vantagem_economica', 'protocolo_sei',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Protocolo de publicação no SEI',
               existing_nullable=True)
    op.alter_column('relatorios_vantagem_economica', 'valor_economia_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Valor economizado (R$)',
               existing_nullable=True)
    op.alter_column('relatorios_vantagem_economica', 'percentual_economia',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Percentual de economia (%)',
               existing_nullable=True)
    op.alter_column('relatorios_vantagem_economica', 'conclusao_tecnica',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Conclusão técnica sobre a vantagem econômica',
               existing_nullable=True)
    op.alter_column('relatorios_vantagem_economica', 'custo_processamento_direto',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Custos administrativos de contratação direta',
               existing_nullable=True)
    op.alter_column('relatorios_vantagem_economica', 'custo_processamento_adesao',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Custos administrativos da adesão',
               existing_nullable=True)
    op.alter_column('relatorios_vantagem_economica', 'comparativo_precos',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='JSON: [{fornecedor, preco_ata, preco_direto, economia_percentual}, ...]',
               existing_nullable=True)
    op.alter_column('pesquisas_precos', 'audit_metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Metadados de auditoria (modelo IA, tokens, timestamp)',
               existing_comment='Metadados de auditoria',
               existing_nullable=True)
    op.alter_column('pesquisas_precos', 'document_header',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Cabecalho do documento (titulo, numero, versao)',
               existing_comment='Cabecalho do documento',
               existing_nullable=True)
    op.alter_column('pesquisas_precos', 'item_descricao',
               existing_type=sa.VARCHAR(length=500),
               comment='Descricao do item principal (ex: Cafe, Acucar)',
               existing_comment='Descricao do item principal',
               existing_nullable=True)
    op.alter_column('minuta_contrato', 'protocolo_sei',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Protocolo de publicação no SEI',
               existing_nullable=True)
    op.alter_column('minuta_contrato', 'foro_competente',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Foro competente para dirimir conflitos',
               existing_nullable=True)
    op.alter_column('minuta_contrato', 'lei_aplicavel',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Lei e regulamentos aplicáveis ao contrato',
               existing_nullable=True)
    op.alter_column('minuta_contrato', 'penalidades',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Penalidades por descumprimento',
               existing_nullable=True)
    op.alter_column('minuta_contrato', 'rescisao',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Condições de rescisão do contrato',
               existing_nullable=True)
    op.alter_column('minuta_contrato', 'valor_garantia',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Valor da garantia em R$',
               existing_nullable=True)
    op.alter_column('minuta_contrato', 'percentual_garantia',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Percentual sobre o valor do contrato (ex: 5%)',
               existing_nullable=True)
    op.alter_column('minuta_contrato', 'tipo_garantia',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Ex: 'Seguro-garantia, caução em dinheiro, fiança bancária'",
               existing_nullable=True)
    op.alter_column('minuta_contrato', 'exige_garantia',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Enum: sim, nao',
               existing_nullable=True)
    op.alter_column('minuta_contrato', 'prazo_maximo_prorrogacao',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Ex: 'Até 60 meses conforme Art. 107 da Lei 14.133/21'",
               existing_nullable=True)
    op.alter_column('minuta_contrato', 'condicoes_prorrogacao',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Condições para prorrogação do contrato',
               existing_nullable=True)
    op.alter_column('minuta_contrato', 'possibilidade_prorrogacao',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Enum: sim, nao',
               existing_nullable=True)
    op.alter_column('minuta_contrato', 'prazo_vigencia',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Ex: '12 meses'",
               existing_nullable=True)
    op.alter_column('minuta_contrato', 'data_termino',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Data de término do contrato',
               existing_nullable=True)
    op.alter_column('minuta_contrato', 'data_inicio',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Data de início do contrato',
               existing_nullable=True)
    op.alter_column('minuta_contrato', 'fluxo_liquidacao',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Fluxo de liquidação e emissão de nota fiscal',
               existing_nullable=True)
    op.alter_column('minuta_contrato', 'prazo_pagamento',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Ex: '30 dias após apresentação da nota fiscal'",
               existing_nullable=True)
    op.alter_column('minuta_contrato', 'forma_pagamento',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Descrição da forma de pagamento',
               existing_nullable=True)
    op.alter_column('minuta_contrato', 'obrigacoes_estruturadas',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='JSON: {contratada: [{clausula, descricao}, ...], contratante: [{clausula, descricao}, ...]}',
               existing_nullable=True)
    op.alter_column('minuta_contrato', 'obrigacoes_contratante',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Responsabilidades da contratante',
               existing_nullable=True)
    op.alter_column('minuta_contrato', 'obrigacoes_contratada',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Responsabilidades da contratada',
               existing_nullable=True)
    op.alter_column('minuta_contrato', 'edital_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Edital ao qual esta minuta está vinculada',
               existing_nullable=True)
    op.alter_column('justificativas_vantagem_adesao', 'protocolo_sei',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Protocolo de publicação no SEI',
               existing_nullable=True)
    op.alter_column('justificativas_vantagem_adesao', 'declaracao_conformidade',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Declara conformidade com Lei 14.133/21 e regulamentos internos',
               existing_nullable=True)
    op.alter_column('justificativas_vantagem_adesao', 'justificativa_conveniencia',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Por que adesão é mais conveniente que contratação direta',
               existing_nullable=True)
    op.alter_column('justificativas_vantagem_adesao', 'fundamentacao_legal',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Citação da Lei 14.133/21, Art. 37 e jurisprudência aplicável',
               existing_nullable=True)
    op.alter_column('justificativas_preco_escolha', 'protocolo_sei',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Protocolo de publicação no SEI',
               existing_nullable=True)
    op.alter_column('justificativas_preco_escolha', 'preco_final_contratacao',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Preço final negociado para a contratação',
               existing_nullable=True)
    op.alter_column('justificativas_preco_escolha', 'analise_preco_praticado',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Análise do preço praticado vs mercado',
               existing_nullable=True)
    op.alter_column('justificativas_preco_escolha', 'justificativa_fornecedor',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Motivos da escolha deste fornecedor específico',
               existing_nullable=True)
    op.alter_column('justificativa_fornecedor_escolhido', 'protocolo_sei',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Protocolo de publicação no SEI',
               existing_nullable=True)
    op.alter_column('justificativa_fornecedor_escolhido', 'conclusao_justificativa',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Conclusão sobre a adequação do fornecedor e a conformidade da escolha',
               existing_nullable=True)
    op.alter_column('justificativa_fornecedor_escolhido', 'valores_referencia',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='JSON: [{fonte, valor, data}, ...] - Valores de referência para comparação',
               existing_nullable=True)
    op.alter_column('justificativa_fornecedor_escolhido', 'analise_compatibilidade_preco',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Análise de compatibilidade do preço com valores de mercado',
               existing_nullable=True)
    op.alter_column('justificativa_fornecedor_escolhido', 'preco_proposto',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Preço proposto pelo fornecedor escolhido',
               existing_nullable=True)
    op.alter_column('justificativa_fornecedor_escolhido', 'documentacao_exclusividade',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='JSON: [{tipo_documento, descricao, arquivo}, ...] - Documentos que comprovam exclusividade',
               existing_nullable=True)
    op.alter_column('justificativa_fornecedor_escolhido', 'tipo_inviabilidade',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Ex: 'Fornecedor Exclusivo', 'Notória Especialização', 'Artista Consagrado'",
               existing_nullable=True)
    op.alter_column('justificativa_fornecedor_escolhido', 'justificativa_inviabilidade',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Explicação de por que não é possível licitar (ex: fornecedor exclusivo, artista consagrado)',
               existing_nullable=True)
    op.alter_column('justificativa_fornecedor_escolhido', 'inviabilidade_competicao',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Enum: sim, nao',
               existing_nullable=True)
    op.alter_column('justificativa_fornecedor_escolhido', 'certidoes_anexadas',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='JSON: [{tipo, arquivo, data_upload}, ...] - Conjunto completo de certidões',
               existing_nullable=True)
    op.alter_column('justificativa_fornecedor_escolhido', 'certidao_trabalhista',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='JSON: {numero, data_emissao, validade, situacao}',
               existing_nullable=True)
    op.alter_column('justificativa_fornecedor_escolhido', 'certidao_fgts',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='JSON: {numero, data_emissao, validade, situacao}',
               existing_nullable=True)
    op.alter_column('justificativa_fornecedor_escolhido', 'certidao_municipal',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='JSON: {numero, data_emissao, validade, situacao}',
               existing_nullable=True)
    op.alter_column('justificativa_fornecedor_escolhido', 'certidao_estadual',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='JSON: {numero, data_emissao, validade, situacao}',
               existing_nullable=True)
    op.alter_column('justificativa_fornecedor_escolhido', 'certidao_federal',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='JSON: {numero, data_emissao, validade, situacao}',
               existing_nullable=True)
    op.alter_column('justificativa_fornecedor_escolhido', 'experiencia_comprovada',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Descrição da experiência comprovada do fornecedor',
               existing_nullable=True)
    op.alter_column('justificativa_fornecedor_escolhido', 'atestados_capacidade',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='JSON: [{tipo_atestado, descricao, data_emissao, orgao_emissor}, ...]',
               existing_nullable=True)
    op.alter_column('justificativa_fornecedor_escolhido', 'qualificacao_tecnica',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Provas de expertise única ou capacidade imediata',
               existing_nullable=True)
    op.alter_column('justificativa_fornecedor_escolhido', 'endereco_fornecedor',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Endereço completo do fornecedor',
               existing_nullable=True)
    op.alter_column('justificativa_fornecedor_escolhido', 'cnpj_fornecedor',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='CNPJ do fornecedor',
               existing_nullable=True)
    op.alter_column('justificativa_fornecedor_escolhido', 'nome_fornecedor',
               existing_type=sa.VARCHAR(length=300),
               comment=None,
               existing_comment='Razão social do fornecedor escolhido',
               existing_nullable=True)
    op.alter_column('justificativa_fornecedor_escolhido', 'aviso_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Aviso de dispensa vinculado',
               existing_nullable=True)
    op.alter_column('itens_risco', 'notas',
               existing_type=sa.TEXT(),
               comment='Anotações adicionais ou mudanças de status',
               existing_nullable=True)
    op.alter_column('itens_risco', 'criado_por',
               existing_type=sa.INTEGER(),
               comment='Quem criou: usuário ou IA?',
               existing_nullable=True)
    op.alter_column('itens_risco', 'responsavel_monitoramento',
               existing_type=sa.VARCHAR(length=100),
               comment="Quem monitora? Ex: 'Gestor do Contrato'",
               existing_nullable=True)
    op.alter_column('itens_risco', 'gatilho_monitoramento',
               existing_type=sa.TEXT(),
               comment="Sinal de alerta. Ex: 'Atraso de mais de 5 dias no cronograma'",
               existing_nullable=True)
    op.alter_column('itens_risco', 'alocacao_responsavel',
               existing_type=sa.VARCHAR(length=50),
               comment='Enum: Contratante, Contratada, Compartilhado. Quem paga a conta?',
               existing_comment='Enum: Contratante, Contratada, Compartilhado',
               existing_nullable=True)
    op.alter_column('itens_risco', 'acoes_contingencia',
               existing_type=sa.TEXT(),
               comment="Fazer SE OCORRER. Ex: 'Acionar fornecedor número 2'",
               existing_nullable=True)
    op.alter_column('itens_risco', 'acoes_preventivas',
               existing_type=sa.TEXT(),
               comment="Fazer ANTES para evitar. Ex: 'Exigir atestado técnico rigoroso'",
               existing_nullable=True)
    op.alter_column('itens_risco', 'justificativa_impacto',
               existing_type=sa.TEXT(),
               comment="Ex: 'Atraso de 1 mês = perda de 30 dias de serviço. Impacto em X% da operação'",
               existing_nullable=True)
    op.alter_column('itens_risco', 'justificativa_probabilidade',
               existing_type=sa.TEXT(),
               comment="Ex: 'Baseado em histórico: 2 de 5 contratos anteriores atrasaram'",
               existing_nullable=True)
    op.alter_column('itens_risco', 'nivel_risco',
               existing_type=sa.INTEGER(),
               comment='Calculado: probabilidade × impacto (1-25). Mapeado: 1-5=Baixo, 6-10=Médio, 11-20=Alto, 21-25=Extremo',
               existing_comment='Calculado: probabilidade × impacto (1-25)',
               existing_nullable=True)
    op.alter_column('itens_risco', 'impacto',
               existing_type=sa.INTEGER(),
               comment='1-5: 1=Irrelevante, 3=Médio, 5=Catastrófico',
               existing_comment='1-5: 1=Irrelevante, 5=Catastrófico',
               existing_nullable=True)
    op.alter_column('itens_risco', 'probabilidade',
               existing_type=sa.INTEGER(),
               comment='1-5: 1=Improvável, 3=Médio, 5=Muito provável',
               existing_comment='1-5: 1=Improvável, 5=Muito provável',
               existing_nullable=True)
    op.alter_column('itens_risco', 'consequencia',
               existing_type=sa.TEXT(),
               comment="QUAL IMPACTO? Ex: 'Paralisação do serviço público'",
               existing_comment='QUAL IMPACTO?',
               existing_nullable=True)
    op.alter_column('itens_risco', 'causa',
               existing_type=sa.TEXT(),
               comment="POR QUÊ? IA preenche analisando DFD+Cotações. Ex: 'Cotação com cronograma otimista'",
               existing_comment='POR QUÊ?',
               existing_nullable=True)
    op.alter_column('itens_risco', 'evento',
               existing_type=sa.TEXT(),
               comment="O QUÊ pode acontecer? Ex: 'Fornecedor não entregar no prazo'",
               existing_comment='O QUÊ pode acontecer?',
               existing_nullable=True)
    op.alter_column('itens_risco', 'origem',
               existing_type=sa.VARCHAR(length=50),
               comment='Enum: DFD, Cotacao, PAC, Externo. Rastreabilidade da IA.',
               existing_comment='Enum: DFD, Cotacao, PAC, Externo',
               existing_nullable=True)
    op.drop_column('itens_risco', 'protocolo_sei')
    op.drop_column('itens_risco', 'data_aprovacao')
    op.drop_column('itens_risco', 'campos_regenerados')
    op.drop_column('itens_risco', 'campos_editados')
    op.drop_column('itens_risco', 'metadata_ia')
    op.drop_column('itens_risco', 'prompt_ia')
    op.drop_column('itens_risco', 'gerado_por_ia')
    op.drop_column('itens_risco', 'status')
    op.drop_column('itens_risco', 'versao')
    op.alter_column('etps', 'criterios_analise_modalidade',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='JSON: {valor_limite: float, adesao_atas_disponiveis: bool, etc}',
               existing_nullable=True)
    op.alter_column('etps', 'justificativa_modalidade',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Justificativa técnica/legal para escolha da modalidade',
               existing_nullable=True)
    op.alter_column('etps', 'data_definicao_modalidade',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Data em que modalidade foi definida pelo usuário',
               existing_nullable=True)
    op.alter_column('etps', 'modalidade_definida',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Enum: adesao_ata, dispensa_valor_baixo, licitacao_normal, contratacao_direta',
               existing_nullable=True)
    op.alter_column('etps', 'modalidade_sugerida',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Enum: adesao_ata, dispensa_valor_baixo, licitacao_normal',
               existing_nullable=True)
    op.alter_column('etps', 'deep_research_ativado',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment=None,
               existing_comment='Flag para indicar que deep_research foi automaticamente ativado',
               existing_server_default=sa.text('false'))
    op.alter_column('etps', 'ata_selecionada',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='JSON com dados da ata selecionada',
               existing_nullable=True)
    op.alter_column('etps', 'fase_adesao_ata',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Enum: nao_iniciada, buscando_atas, ata_selecionada, deep_research_ativo, concluida',
               existing_nullable=True)
    op.alter_column('etps', 'adesao_ata_habilitada',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment=None,
               existing_comment='Usuário habilitou busca por adesão em ata de registro de preços',
               existing_server_default=sa.text('false'))
    op.alter_column('etps', 'checklist_conformidade',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='JSON: {valor_presente: bool, parcelamento_justificado: bool, riscos_citados: bool, pca_mencionado: bool}',
               existing_nullable=True)
    op.alter_column('etps', 'sincronizado',
               existing_type=sa.INTEGER(),
               comment='1=sincronizado, 0=módulo fonte alterado, precisa revisão',
               existing_comment='1=sincronizado, 0=módulo fonte alterado',
               existing_nullable=True)
    op.alter_column('etps', 'contratacoes_correlatas',
               existing_type=sa.TEXT(),
               comment='Contratações interdependentes (ex: Ar Condicionado -> Instalação Elétrica)',
               existing_comment='Contratações interdependentes',
               existing_nullable=True)
    op.alter_column('etps', 'solucao_escolhida',
               existing_type=sa.VARCHAR(length=200),
               comment='Nome/tipo da solução escolhida: Compra, Locação, SaaS, etc',
               existing_comment='Nome/tipo da solução escolhida',
               existing_nullable=True)
    op.alter_column('checklist_conformidade', 'protocolo_sei',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Protocolo de publicação no SEI',
               existing_nullable=True)
    op.alter_column('checklist_conformidade', 'status_conformidade',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Enum: conforme, nao_conforme, conforme_com_ressalvas',
               existing_nullable=True)
    op.alter_column('checklist_conformidade', 'observacoes_gerais',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Observações ou pendências identificadas',
               existing_nullable=True)
    op.alter_column('checklist_conformidade', 'assinatura_eletronica',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='JSON: {nome, cargo, cpf, data, hash_assinatura}',
               existing_nullable=True)
    op.alter_column('checklist_conformidade', 'validado_por',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Nome e cargo da autoridade que validou',
               existing_nullable=True)
    op.alter_column('checklist_conformidade', 'parecer_juridico_presente',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Enum: sim, nao, nao_se_aplica',
               existing_nullable=True)
    op.alter_column('checklist_conformidade', 'disponibilidade_orcamentaria_presente',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Enum: sim, nao, nao_se_aplica',
               existing_nullable=True)
    op.alter_column('checklist_conformidade', 'matriz_riscos_presente',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Enum: sim, nao, nao_se_aplica',
               existing_nullable=True)
    op.alter_column('checklist_conformidade', 'tr_presente',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Enum: sim, nao, nao_se_aplica',
               existing_nullable=True)
    op.alter_column('checklist_conformidade', 'etp_presente',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Enum: sim, nao, nao_se_aplica',
               existing_nullable=True)
    op.alter_column('checklist_conformidade', 'dfd_folhas',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Referência de páginas/ID no processo',
               existing_nullable=True)
    op.alter_column('checklist_conformidade', 'dfd_presente',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Enum: sim, nao, nao_se_aplica',
               existing_nullable=True)
    op.alter_column('checklist_conformidade', 'itens_verificacao',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='JSON: [{item, descricao, status, referencia_folhas, observacoes}, ...]. Status: sim/nao/nao_se_aplica',
               existing_nullable=True)
    op.alter_column('checklist_conformidade', 'tr_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='TR vinculado ao checklist',
               existing_nullable=True)
    op.alter_column('certidoes_enquadramento', 'protocolo_sei',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Protocolo de publicação no SEI',
               existing_nullable=True)
    op.alter_column('certidoes_enquadramento', 'responsavel_certificacao',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Nome e cargo do responsável',
               existing_nullable=True)
    op.alter_column('certidoes_enquadramento', 'artigo_lei_aplicavel',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Artigo da Lei 14.133/21 aplicável (ex: Art. 75, I)',
               existing_nullable=True)
    op.alter_column('certidoes_enquadramento', 'conclusao_enquadramento',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Conclusão sobre o enquadramento legal',
               existing_nullable=True)
    op.alter_column('certidoes_enquadramento', 'valor_contratacao_analisada',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Valor da contratação analisada',
               existing_nullable=True)
    op.alter_column('certidoes_enquadramento', 'limite_legal_aplicavel',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Limite legal para enquadramento (ex: R$ 8.800)',
               existing_nullable=True)
    op.alter_column('avisos_dispensa_eletronica', 'protocolo_sei',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Protocolo de publicação no SEI',
               existing_nullable=True)
    op.alter_column('avisos_dispensa_eletronica', 'protocolo_publicacao',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Número de protocolo do aviso publicado',
               existing_nullable=True)
    op.alter_column('avisos_dispensa_eletronica', 'link_portal',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='URL do aviso no portal eletrônico',
               existing_nullable=True)
    op.alter_column('avisos_dispensa_eletronica', 'data_publicacao',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Data de publicação no portal eletrônico',
               existing_nullable=True)
    op.alter_column('avisos_dispensa_eletronica', 'numero_aviso',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Número do aviso atribuído pelo portal',
               existing_nullable=True)
    op.alter_column('aviso_publicidade_direta', 'protocolo_sei',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Protocolo de publicação no SEI',
               existing_nullable=True)
    op.alter_column('aviso_publicidade_direta', 'extrato_aviso',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Extrato resumido do aviso publicado',
               existing_nullable=True)
    op.alter_column('aviso_publicidade_direta', 'numero_aviso',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Número de identificação do aviso',
               existing_nullable=True)
    op.alter_column('aviso_publicidade_direta', 'link_site_orgao',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Link para o aviso no site do órgão',
               existing_nullable=True)
    op.alter_column('aviso_publicidade_direta', 'data_publicacao_site_orgao',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Data de publicação no site do órgão',
               existing_nullable=True)
    op.alter_column('aviso_publicidade_direta', 'link_pncp',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Link para o aviso no Portal Nacional de Contratações Públicas',
               existing_nullable=True)
    op.alter_column('aviso_publicidade_direta', 'data_publicacao_pncp',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Data de publicação no PNCP',
               existing_nullable=True)
    op.alter_column('aviso_publicidade_direta', 'data_fim_prazo',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Data de término do prazo para manifestação',
               existing_nullable=True)
    op.alter_column('aviso_publicidade_direta', 'data_inicio_prazo',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Data de início do prazo para manifestação',
               existing_nullable=True)
    op.alter_column('aviso_publicidade_direta', 'prazo_manifestacao_dias',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Número de dias úteis para manifestação (mínimo 3 para dispensa eletrônica)',
               existing_nullable=True)
    op.alter_column('aviso_publicidade_direta', 'metodologia_valor',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Como foi calculado o valor estimado',
               existing_nullable=True)
    op.alter_column('aviso_publicidade_direta', 'valor_estimado',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Teto que a administração se propõe a pagar',
               existing_nullable=True)
    op.alter_column('aviso_publicidade_direta', 'justificativa_legal',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Explicação do enquadramento na hipótese de dispensa',
               existing_nullable=True)
    op.alter_column('aviso_publicidade_direta', 'artigo_lei',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="Ex: 'Art. 75, II' ou 'Art. 74, I'",
               existing_nullable=True)
    op.alter_column('aviso_publicidade_direta', 'fundamento_legal',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Inciso específico do Art. 75 ou Art. 74 da Lei 14.133/21',
               existing_nullable=True)
    op.alter_column('aviso_publicidade_direta', 'tr_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='TR vinculado ao aviso',
               existing_nullable=True)
    op.drop_index(op.f('ix_portarias_designacao_id'), table_name='portarias_designacao')
    op.drop_table('portarias_designacao')
    # ### end Alembic commands ###
