"""complete_schema_create_all_tables

Revision ID: 344757b4a346
Revises: 3a6a231de138
Create Date: 2026-02-02 01:02:16.883554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '344757b4a346'
down_revision: Union[str, None] = '3a6a231de138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pac',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID único do item do PAC'),
    sa.Column('ano', sa.Integer(), nullable=False, comment='Ano do planejamento (ex: 2025)'),
    sa.Column('tipo_pac', sa.String(length=50), nullable=True, comment='Tipo: Ordinário, Extraordinário, etc'),
    sa.Column('iniciativa', sa.Text(), nullable=True, comment='Iniciativa estratégica do PEI'),
    sa.Column('objetivo', sa.Text(), nullable=True, comment='Objetivo estratégico do PEI'),
    sa.Column('unidade_tecnica', sa.String(length=200), nullable=True, comment='Unidade técnica responsável'),
    sa.Column('unidade_administrativa', sa.String(length=200), nullable=True, comment='Unidade administrativa responsável'),
    sa.Column('detalhamento', sa.Text(), nullable=False, comment='Descrição detalhada do objeto'),
    sa.Column('descricao', sa.String(length=500), nullable=True, comment='Descrição resumida'),
    sa.Column('quantidade', sa.Float(), nullable=True, comment='Quantidade a ser contratada'),
    sa.Column('unidade', sa.String(length=50), nullable=True, comment='Unidade de medida (kg, unidade, litro, etc)'),
    sa.Column('frequencia', sa.String(length=50), nullable=True, comment='Frequência (ANUAL, MENSAL, etc)'),
    sa.Column('valor_previsto', sa.String(length=50), nullable=True, comment='Valor previsto (texto com R$)'),
    sa.Column('justificativa', sa.Text(), nullable=True, comment='Justificativa da contratação'),
    sa.Column('prioridade', sa.Integer(), nullable=True, comment='Nível de prioridade (1-5)'),
    sa.Column('data_tr', sa.String(length=20), nullable=True, comment='Data de TR'),
    sa.Column('disponibilidade_contratacao', sa.String(length=20), nullable=True, comment='Data de disponibilidade'),
    sa.Column('numero_contrato', sa.String(length=50), nullable=True, comment='Número do contrato vigente'),
    sa.Column('ano_contrato', sa.String(length=10), nullable=True, comment='Ano do contrato'),
    sa.Column('vencimento_contrato', sa.String(length=20), nullable=True, comment='Data de vencimento'),
    sa.Column('prorrogacao_contrato', sa.String(length=10), nullable=True, comment='Número de prorrogações'),
    sa.Column('contratacao_continuada', sa.String(length=10), nullable=True, comment='Se é contratação continuada (Sim/Não)'),
    sa.Column('catmat_catser', sa.String(length=50), nullable=True, comment='Código CATMAT/CATSER'),
    sa.Column('despesa', sa.String(length=200), nullable=True, comment='Tipo de despesa'),
    sa.Column('elemento_despesa', sa.String(length=200), nullable=True, comment='Elemento de despesa'),
    sa.Column('natureza_despesa', sa.String(length=100), nullable=True, comment='Natureza da despesa'),
    sa.Column('inativo', sa.String(length=10), nullable=True, comment='Se o item está inativo (Sim/Não)'),
    sa.Column('motivo_rejeicao', sa.Text(), nullable=True, comment='Motivo da rejeição, se houver'),
    sa.Column('motivo_ajuste', sa.Text(), nullable=True, comment='Motivo do ajuste, se houver'),
    sa.Column('numero_pad', sa.String(length=50), nullable=True, comment='Número do PAD'),
    sa.Column('ano_pad', sa.String(length=10), nullable=True, comment='Ano do PAD'),
    sa.Column('tipo_contratacao', sa.String(length=100), nullable=True, comment='Tipo: Serviços, Fornecimento, etc'),
    sa.Column('fase', sa.String(length=50), nullable=True, comment='Fase atual do item (AJUSTES, etc)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pac_ano'), 'pac', ['ano'], unique=False)
    op.create_index(op.f('ix_pac_id'), 'pac', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('setor', sa.String(length=200), nullable=True),
    sa.Column('grupo', sa.String(length=100), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('ultimo_acesso', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('projetos',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID único do projeto'),
    sa.Column('titulo', sa.String(length=300), nullable=False, comment='Título descritivo do projeto'),
    sa.Column('descricao', sa.Text(), nullable=True, comment='Descrição detalhada do projeto'),
    sa.Column('usuario_id', sa.Integer(), nullable=False, comment='ID do usuário que criou o projeto'),
    sa.Column('prompt_inicial', sa.Text(), nullable=True, comment='Prompt inicial fornecido pelo usuário para a IA'),
    sa.Column('itens_pac', sa.JSON(), nullable=True, comment="Lista de itens PAC: [{'id': 8, 'quantidade': 100}, ...]. Quantidade é específica do projeto."),
    sa.Column('protocolo_sei', sa.JSON(), nullable=True, comment='Dados do protocolo SEI: numero, assunto, link, etc.'),
    sa.Column('arquivado', sa.Integer(), nullable=False, comment='Define se o projeto está arquivado (1) ou ativo (0)'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Status: rascunho, em_andamento, concluido, cancelado'),
    sa.Column('data_criacao', sa.DateTime(), nullable=False, comment='Data de criação do projeto'),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False, comment='Data da última atualização'),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True, comment='Data de conclusão do projeto'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projetos_id'), 'projetos', ['id'], unique=False)
    op.create_table('dfds',
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('descricao_objeto', sa.Text(), nullable=True),
    sa.Column('justificativa', sa.Text(), nullable=True),
    sa.Column('alinhamento_estrategico', sa.Text(), nullable=True),
    sa.Column('valor_estimado', sa.Float(), nullable=True),
    sa.Column('cronograma', sa.Text(), nullable=True),
    sa.Column('responsavel_requisitante', sa.String(length=200), nullable=True),
    sa.Column('responsavel_gestor', sa.String(length=200), nullable=True),
    sa.Column('responsavel_fiscal', sa.String(length=200), nullable=True),
    sa.Column('setor_requisitante', sa.String(length=200), nullable=True),
    sa.Column('grau_prioridade', sa.String(length=50), nullable=True),
    sa.Column('data_pretendida', sa.Date(), nullable=True),
    sa.Column('alinhamento_pca', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('gerado_por_ia', sa.Boolean(), nullable=True),
    sa.Column('prompt_ia', sa.Text(), nullable=True),
    sa.Column('metadata_ia', sa.JSON(), nullable=True),
    sa.Column('campos_editados', sa.JSON(), nullable=True),
    sa.Column('campos_regenerados', sa.JSON(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('data_aprovacao', sa.DateTime(), nullable=True),
    sa.Column('protocolo_sei', sa.JSON(), nullable=True, comment='Protocolo de publicação no SEI'),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dfds_id'), 'dfds', ['id'], unique=False)
    op.create_table('editais',
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('objeto', sa.Text(), nullable=True),
    sa.Column('condicoes_participacao', sa.Text(), nullable=True),
    sa.Column('criterios_julgamento', sa.Text(), nullable=True),
    sa.Column('fase_lances', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('gerado_por_ia', sa.Boolean(), nullable=True),
    sa.Column('prompt_ia', sa.Text(), nullable=True),
    sa.Column('metadata_ia', sa.JSON(), nullable=True),
    sa.Column('campos_editados', sa.JSON(), nullable=True),
    sa.Column('campos_regenerados', sa.JSON(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('data_aprovacao', sa.DateTime(), nullable=True),
    sa.Column('protocolo_sei', sa.JSON(), nullable=True, comment='Protocolo de publicação no SEI'),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_editais_id'), 'editais', ['id'], unique=False)
    op.create_table('etps',
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('descricao_necessidade', sa.Text(), nullable=True),
    sa.Column('requisitos_tecnicos', sa.Text(), nullable=True),
    sa.Column('levantamento_mercado', sa.Text(), nullable=True),
    sa.Column('estimativa_valor', sa.Text(), nullable=True),
    sa.Column('viabilidade', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('gerado_por_ia', sa.Boolean(), nullable=True),
    sa.Column('prompt_ia', sa.Text(), nullable=True),
    sa.Column('metadata_ia', sa.JSON(), nullable=True),
    sa.Column('campos_editados', sa.JSON(), nullable=True),
    sa.Column('campos_regenerados', sa.JSON(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('data_aprovacao', sa.DateTime(), nullable=True),
    sa.Column('protocolo_sei', sa.JSON(), nullable=True, comment='Protocolo de publicação no SEI'),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etps_id'), 'etps', ['id'], unique=False)
    op.create_table('pesquisas_precos',
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('artefatos_base', sa.JSON(), nullable=True, comment='IDs dos artefatos (DFDs) usados como base'),
    sa.Column('content_blocks', sa.JSON(), nullable=True, comment='Estrutura JSON completa da pesquisa'),
    sa.Column('dados_cotacao', sa.JSON(), nullable=True, comment='JSON bruto retornado pela api_compras'),
    sa.Column('valor_total_cotacao', sa.Float(), nullable=True, comment='Valor total consolidado da cotacao'),
    sa.Column('itens_cotados', sa.JSON(), nullable=True, comment='Lista de itens cotados'),
    sa.Column('fornecedores_selecionados', sa.JSON(), nullable=True, comment='Lista de fornecedores selecionados'),
    sa.Column('item_descricao', sa.String(length=500), nullable=True, comment='Descricao do item principal (ex: Cafe, Acucar)'),
    sa.Column('preco_medio', sa.Float(), nullable=True, comment='Preco medio calculado'),
    sa.Column('quantidade_itens_encontrados', sa.Integer(), nullable=True, comment='Quantidade de precos encontrados'),
    sa.Column('document_header', sa.JSON(), nullable=True, comment='Cabecalho do documento (titulo, numero, versao)'),
    sa.Column('audit_metadata', sa.JSON(), nullable=True, comment='Metadados de auditoria (modelo IA, tokens, timestamp)'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('gerado_por_ia', sa.Boolean(), nullable=True),
    sa.Column('prompt_ia', sa.Text(), nullable=True),
    sa.Column('metadata_ia', sa.JSON(), nullable=True),
    sa.Column('campos_editados', sa.JSON(), nullable=True),
    sa.Column('campos_regenerados', sa.JSON(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('data_aprovacao', sa.DateTime(), nullable=True),
    sa.Column('protocolo_sei', sa.JSON(), nullable=True, comment='Protocolo de publicação no SEI'),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pesquisas_precos_id'), 'pesquisas_precos', ['id'], unique=False)
    op.create_table('riscos',
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('artefatos_base', sa.JSON(), nullable=True, comment='IDs dos artefatos usados na análise: {dfd_id: [1,2,3], etp_id: 5, cotacao_id: 7}'),
    sa.Column('identificacao_objeto', sa.Text(), nullable=True, comment="Resumo do que está sendo licitado (ex: 'Aquisição de Servidor Web')"),
    sa.Column('valor_estimado_total', sa.Float(), nullable=True, comment='Valor total estimado derivado de cotações/ETP'),
    sa.Column('metodologia_adotada', sa.String(length=100), nullable=True, comment="Ex: 'Matriz 5x5', 'ISO 31000'"),
    sa.Column('data_revisao', sa.Date(), nullable=True, comment='Última revisão do PGR'),
    sa.Column('equipe_responsavel', sa.JSON(), nullable=True, comment="JSON: [{nome: 'João', cargo: 'Analista'}, ...]"),
    sa.Column('resumo_analise_planejamento', sa.Text(), nullable=True, comment='Sumarização de riscos da fase de planejamento'),
    sa.Column('resumo_analise_selecao', sa.Text(), nullable=True, comment='Sumarização de riscos da fase de seleção'),
    sa.Column('resumo_analise_gestao', sa.Text(), nullable=True, comment='Sumarização de riscos da fase de gestão contratual'),
    sa.Column('plano_comunicacao', sa.JSON(), nullable=True, comment='JSON: [{stakeholder, formato, frequencia, conteudo}, ...]'),
    sa.Column('matriz_alocacao', sa.JSON(), nullable=True, comment='Agrupa riscos por alocacao_responsavel: {Contratante: [...], Contratada: [...], Compartilhado: [...]}'),
    sa.Column('mapa_calor', sa.JSON(), nullable=True, comment='JSON estruturado para renderizar matriz de prob vs impacto'),
    sa.Column('content_blocks', sa.JSON(), nullable=True, comment='Estrutura JSON completa (legado)'),
    sa.Column('document_header', sa.JSON(), nullable=True, comment='Cabecalho do documento (titulo, numero, versao)'),
    sa.Column('audit_metadata', sa.JSON(), nullable=True, comment='Metadados de auditoria (modelo IA, tokens, timestamp)'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('gerado_por_ia', sa.Boolean(), nullable=True),
    sa.Column('prompt_ia', sa.Text(), nullable=True),
    sa.Column('metadata_ia', sa.JSON(), nullable=True),
    sa.Column('campos_editados', sa.JSON(), nullable=True),
    sa.Column('campos_regenerados', sa.JSON(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('data_aprovacao', sa.DateTime(), nullable=True),
    sa.Column('protocolo_sei', sa.JSON(), nullable=True, comment='Protocolo de publicação no SEI'),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_riscos_id'), 'riscos', ['id'], unique=False)
    op.create_table('trs',
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('definicao_objeto', sa.Text(), nullable=True),
    sa.Column('justificativa', sa.Text(), nullable=True),
    sa.Column('especificacao_tecnica', sa.Text(), nullable=True),
    sa.Column('obrigacoes', sa.Text(), nullable=True),
    sa.Column('criterios_aceitacao', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('gerado_por_ia', sa.Boolean(), nullable=True),
    sa.Column('prompt_ia', sa.Text(), nullable=True),
    sa.Column('metadata_ia', sa.JSON(), nullable=True),
    sa.Column('campos_editados', sa.JSON(), nullable=True),
    sa.Column('campos_regenerados', sa.JSON(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('data_aprovacao', sa.DateTime(), nullable=True),
    sa.Column('protocolo_sei', sa.JSON(), nullable=True, comment='Protocolo de publicação no SEI'),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trs_id'), 'trs', ['id'], unique=False)
    op.create_table('itens_risco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pgr_id', sa.Integer(), nullable=False),
    sa.Column('origem', sa.String(length=50), nullable=True, comment='Enum: DFD, Cotacao, PAC, Externo. Rastreabilidade da IA.'),
    sa.Column('fase_licitacao', sa.String(length=50), nullable=True, comment='Enum: Planejamento, Selecao_Fornecedor, Gestao_Contratual'),
    sa.Column('categoria', sa.String(length=50), nullable=True, comment='Enum: Tecnico, Administrativo, Juridico, Economico, Reputacional'),
    sa.Column('evento', sa.Text(), nullable=True, comment="O QUÊ pode acontecer? Ex: 'Fornecedor não entregar no prazo'"),
    sa.Column('causa', sa.Text(), nullable=True, comment="POR QUÊ? IA preenche analisando DFD+Cotações. Ex: 'Cotação com cronograma otimista'"),
    sa.Column('consequencia', sa.Text(), nullable=True, comment="QUAL IMPACTO? Ex: 'Paralisação do serviço público'"),
    sa.Column('probabilidade', sa.Integer(), nullable=True, comment='1-5: 1=Improvável, 3=Médio, 5=Muito provável'),
    sa.Column('impacto', sa.Integer(), nullable=True, comment='1-5: 1=Irrelevante, 3=Médio, 5=Catastrófico'),
    sa.Column('nivel_risco', sa.Integer(), nullable=True, comment='Calculado: probabilidade × impacto (1-25). Mapeado: 1-5=Baixo, 6-10=Médio, 11-20=Alto, 21-25=Extremo'),
    sa.Column('justificativa_probabilidade', sa.Text(), nullable=True, comment="Ex: 'Baseado em histórico: 2 de 5 contratos anteriores atrasaram'"),
    sa.Column('justificativa_impacto', sa.Text(), nullable=True, comment="Ex: 'Atraso de 1 mês = perda de 30 dias de serviço. Impacto em X% da operação'"),
    sa.Column('tipo_tratamento', sa.String(length=50), nullable=True, comment='Enum: Mitigar, Transferir, Aceitar, Evitar'),
    sa.Column('acoes_preventivas', sa.Text(), nullable=True, comment="Fazer ANTES para evitar. Ex: 'Exigir atestado técnico rigoroso'"),
    sa.Column('acoes_contingencia', sa.Text(), nullable=True, comment="Fazer SE OCORRER. Ex: 'Acionar fornecedor número 2'"),
    sa.Column('alocacao_responsavel', sa.String(length=50), nullable=True, comment='Enum: Contratante, Contratada, Compartilhado. Quem paga a conta?'),
    sa.Column('gatilho_monitoramento', sa.Text(), nullable=True, comment="Sinal de alerta. Ex: 'Atraso de mais de 5 dias no cronograma'"),
    sa.Column('responsavel_monitoramento', sa.String(length=100), nullable=True, comment="Quem monitora? Ex: 'Gestor do Contrato'"),
    sa.Column('frequencia_monitoramento', sa.String(length=50), nullable=True, comment='Enum: Semanal, Quinzenal, Mensal, Trimestral'),
    sa.Column('status_risco', sa.String(length=50), nullable=False, comment='Enum: Identificado, Monitorado, Ativado, Mitigado, Fechado'),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.Column('criado_por', sa.Integer(), nullable=True, comment='Quem criou: usuário ou IA?'),
    sa.Column('notas', sa.Text(), nullable=True, comment='Anotações adicionais ou mudanças de status'),
    sa.ForeignKeyConstraint(['criado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['pgr_id'], ['riscos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_risco_id'), 'itens_risco', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itens_risco_id'), table_name='itens_risco')
    op.drop_table('itens_risco')
    op.drop_index(op.f('ix_trs_id'), table_name='trs')
    op.drop_table('trs')
    op.drop_index(op.f('ix_riscos_id'), table_name='riscos')
    op.drop_table('riscos')
    op.drop_index(op.f('ix_pesquisas_precos_id'), table_name='pesquisas_precos')
    op.drop_table('pesquisas_precos')
    op.drop_index(op.f('ix_etps_id'), table_name='etps')
    op.drop_table('etps')
    op.drop_index(op.f('ix_editais_id'), table_name='editais')
    op.drop_table('editais')
    op.drop_index(op.f('ix_dfds_id'), table_name='dfds')
    op.drop_table('dfds')
    op.drop_index(op.f('ix_projetos_id'), table_name='projetos')
    op.drop_table('projetos')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_pac_id'), table_name='pac')
    op.drop_index(op.f('ix_pac_ano'), table_name='pac')
    op.drop_table('pac')
    # ### end Alembic commands ###
