"""add pgr new format fields

Revision ID: 9ecda614cab1
Revises: 93ca473ea37e
Create Date: 2026-02-09 00:07:37.939357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ecda614cab1'
down_revision: Union[str, None] = '93ca473ea37e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('justificativas_excepcionalidade', 'protocolo_sei',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Protocolo de publicação no SEI',
               existing_nullable=True)
    op.drop_index('ix_justificativas_excepcionalidade_projeto_id', table_name='justificativas_excepcionalidade')
    op.add_column('riscos', sa.Column('metodologia_adotada', sa.String(length=100), nullable=True, comment="Ex: 'Matriz 5x5', 'Análise Qualitativa', etc."))
    op.add_column('riscos', sa.Column('resumo_analise_planejamento', sa.Text(), nullable=True, comment='Resumo dos riscos na fase de planejamento'))
    op.add_column('riscos', sa.Column('resumo_analise_selecao', sa.Text(), nullable=True, comment='Resumo dos riscos na fase de seleção de fornecedor'))
    op.add_column('riscos', sa.Column('resumo_analise_gestao', sa.Text(), nullable=True, comment='Resumo dos riscos na fase de gestão contratual'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('riscos', 'resumo_analise_gestao')
    op.drop_column('riscos', 'resumo_analise_selecao')
    op.drop_column('riscos', 'resumo_analise_planejamento')
    op.drop_column('riscos', 'metodologia_adotada')
    op.create_index('ix_justificativas_excepcionalidade_projeto_id', 'justificativas_excepcionalidade', ['projeto_id'], unique=False)
    op.alter_column('justificativas_excepcionalidade', 'protocolo_sei',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Protocolo de publicação no SEI',
               existing_nullable=True)
    # ### end Alembic commands ###
