"""expand_etp_model_lei14133

Revision ID: a07d02bddad2
Revises: 344757b4a346
Create Date: 2026-02-02 23:34:36.822818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a07d02bddad2'
down_revision: Union[str, None] = '344757b4a346'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etps', sa.Column('area_requisitante', sa.String(length=300), nullable=True, comment='Unidade/Setor que demanda a contratação'))
    op.add_column('etps', sa.Column('requisitos_contratacao', sa.Text(), nullable=True, comment='Requisitos técnicos, normas (ISO, ABNT), garantias, certificações'))
    op.add_column('etps', sa.Column('estimativa_quantidades', sa.Text(), nullable=True, comment='Memória de cálculo: (Consumo Médio x 12) + Margem de Segurança'))
    op.add_column('etps', sa.Column('quantidades_detalhadas', sa.JSON(), nullable=True, comment='JSON: [{item, qtd_solicitada, consumo_medio, justificativa}, ...]'))
    op.add_column('etps', sa.Column('cenarios_mercado', sa.JSON(), nullable=True, comment='JSON: [{cenario, descricao, pros, contras, valor_estimado}, ...]'))
    op.add_column('etps', sa.Column('valor_total_estimado', sa.Float(), nullable=True, comment='Valor total em R$'))
    op.add_column('etps', sa.Column('metodologia_preco', sa.String(length=100), nullable=True, comment='Metodologia: media, mediana, menor_preco'))
    op.add_column('etps', sa.Column('data_base_preco', sa.Date(), nullable=True, comment='Data base da pesquisa de preços'))
    op.add_column('etps', sa.Column('cotacao_id_referencia', sa.Integer(), nullable=True, comment='ID da cotação vinculada'))
    op.add_column('etps', sa.Column('descricao_solucao', sa.Text(), nullable=True, comment='Definição do objeto com a solução escolhida do levantamento de mercado'))
    op.add_column('etps', sa.Column('solucao_escolhida', sa.String(length=200), nullable=True, comment='Nome/tipo da solução escolhida: Compra, Locação, SaaS, etc'))
    op.add_column('etps', sa.Column('justificativa_parcelamento', sa.Text(), nullable=True, comment='Análise de divisibilidade: parcelamento ou justificativa para lote único'))
    op.add_column('etps', sa.Column('parcelamento_aplicavel', sa.String(length=20), nullable=True, comment='Enum: sim, nao, parcial'))
    op.add_column('etps', sa.Column('contratacoes_correlatas', sa.Text(), nullable=True, comment='Contratações interdependentes (ex: Ar Condicionado -> Instalação Elétrica)'))
    op.add_column('etps', sa.Column('contratacoes_correlatas_lista', sa.JSON(), nullable=True, comment='JSON: [{objeto, justificativa, processo_sei}, ...]'))
    op.add_column('etps', sa.Column('alinhamento_pca', sa.Text(), nullable=True, comment='Verificação de constância no Plano de Contratações Anual'))
    op.add_column('etps', sa.Column('pca_ano', sa.Integer(), nullable=True, comment='Ano do PCA'))
    op.add_column('etps', sa.Column('pca_item_id', sa.String(length=50), nullable=True, comment='ID do item no PCA'))
    op.add_column('etps', sa.Column('resultados_pretendidos', sa.Text(), nullable=True, comment='Benefícios esperados: economicidade, eficácia, eficiência'))
    op.add_column('etps', sa.Column('providencias_previas', sa.Text(), nullable=True, comment='Ações prévias: adequação de espaço, capacitação, infraestrutura'))
    op.add_column('etps', sa.Column('providencias_checklist', sa.JSON(), nullable=True, comment='JSON: [{providencia, responsavel, prazo, status}, ...]'))
    op.add_column('etps', sa.Column('impactos_ambientais', sa.Text(), nullable=True, comment='Medidas de sustentabilidade, logística reversa, critérios ambientais'))
    op.add_column('etps', sa.Column('criterios_sustentabilidade', sa.JSON(), nullable=True, comment='JSON: [{criterio, aplicavel, justificativa}, ...]'))
    op.add_column('etps', sa.Column('analise_riscos', sa.Text(), nullable=True, comment='Resumo dos riscos Alto/Extremo com mitigadoras'))
    op.add_column('etps', sa.Column('riscos_criticos', sa.JSON(), nullable=True, comment='JSON: [{risco, nivel, probabilidade, impacto, mitigacao}, ...]'))
    op.add_column('etps', sa.Column('pgr_id_referencia', sa.Integer(), nullable=True, comment='ID do PGR vinculado'))
    op.add_column('etps', sa.Column('viabilidade_contratacao', sa.Text(), nullable=True, comment='Declaração formal de viabilidade técnica e econômica'))
    op.add_column('etps', sa.Column('declaracao_viabilidade', sa.String(length=50), nullable=True, comment='Enum: viavel, inviavel, viavel_com_ressalvas'))
    op.add_column('etps', sa.Column('dfd_id_referencia', sa.Integer(), nullable=True, comment='ID do DFD que originou este ETP'))
    op.add_column('etps', sa.Column('sincronizado', sa.Integer(), nullable=True, comment='1=sincronizado, 0=módulo fonte alterado, precisa revisão'))
    op.add_column('etps', sa.Column('checklist_conformidade', sa.JSON(), nullable=True, comment='JSON: {valor_presente: bool, parcelamento_justificado: bool, riscos_citados: bool, pca_mencionado: bool}'))
    op.add_column('etps', sa.Column('responsaveis', sa.JSON(), nullable=True, comment='JSON: [{nome, cargo, data_assinatura}, ...]'))
    op.alter_column('etps', 'descricao_necessidade',
               existing_type=sa.TEXT(),
               comment='Fundamentação do interesse público e impacto da não-contratação',
               existing_nullable=True)
    op.alter_column('etps', 'levantamento_mercado',
               existing_type=sa.TEXT(),
               comment='Análise comparativa de soluções: Compra vs Locação, SaaS vs Perpétua, etc',
               existing_nullable=True)
    op.alter_column('etps', 'estimativa_valor',
               existing_type=sa.TEXT(),
               comment='Valor global/unitário com descrição da metodologia (Média, Mediana, Menor)',
               existing_nullable=True)
    op.drop_column('etps', 'requisitos_tecnicos')
    op.drop_column('etps', 'viabilidade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etps', sa.Column('viabilidade', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('etps', sa.Column('requisitos_tecnicos', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('etps', 'estimativa_valor',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Valor global/unitário com descrição da metodologia (Média, Mediana, Menor)',
               existing_nullable=True)
    op.alter_column('etps', 'levantamento_mercado',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Análise comparativa de soluções: Compra vs Locação, SaaS vs Perpétua, etc',
               existing_nullable=True)
    op.alter_column('etps', 'descricao_necessidade',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Fundamentação do interesse público e impacto da não-contratação',
               existing_nullable=True)
    op.drop_column('etps', 'responsaveis')
    op.drop_column('etps', 'checklist_conformidade')
    op.drop_column('etps', 'sincronizado')
    op.drop_column('etps', 'dfd_id_referencia')
    op.drop_column('etps', 'declaracao_viabilidade')
    op.drop_column('etps', 'viabilidade_contratacao')
    op.drop_column('etps', 'pgr_id_referencia')
    op.drop_column('etps', 'riscos_criticos')
    op.drop_column('etps', 'analise_riscos')
    op.drop_column('etps', 'criterios_sustentabilidade')
    op.drop_column('etps', 'impactos_ambientais')
    op.drop_column('etps', 'providencias_checklist')
    op.drop_column('etps', 'providencias_previas')
    op.drop_column('etps', 'resultados_pretendidos')
    op.drop_column('etps', 'pca_item_id')
    op.drop_column('etps', 'pca_ano')
    op.drop_column('etps', 'alinhamento_pca')
    op.drop_column('etps', 'contratacoes_correlatas_lista')
    op.drop_column('etps', 'contratacoes_correlatas')
    op.drop_column('etps', 'parcelamento_aplicavel')
    op.drop_column('etps', 'justificativa_parcelamento')
    op.drop_column('etps', 'solucao_escolhida')
    op.drop_column('etps', 'descricao_solucao')
    op.drop_column('etps', 'cotacao_id_referencia')
    op.drop_column('etps', 'data_base_preco')
    op.drop_column('etps', 'metodologia_preco')
    op.drop_column('etps', 'valor_total_estimado')
    op.drop_column('etps', 'cenarios_mercado')
    op.drop_column('etps', 'quantidades_detalhadas')
    op.drop_column('etps', 'estimativa_quantidades')
    op.drop_column('etps', 'requisitos_contratacao')
    op.drop_column('etps', 'area_requisitante')
    # ### end Alembic commands ###
