"""Add perfil column to users

Revision ID: e9d598ac5740
Revises: a07d02bddad2
Create Date: 2026-02-06 02:36:27.634416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9d598ac5740'
down_revision: Union[str, None] = 'a07d02bddad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('perfil', sa.String(length=50), nullable=False, server_default='operador'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'perfil')
    # ### end Alembic commands ###
